# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file

# Extra configuration directory where the config files overriding this file
# should be.
extra_config_files: '/etc/wazo-upgrade/conf.d'

db_uri: postgresql://asterisk:proformatique@localhost/asterisk

auth:
  host: localhost
  port: 9497
  verify_certificate: /usr/share/xivo-certs/server.crt

bus:
  username: guest
  password: guest
  host: localhost
  port: 5672
  exchange_name: xivo
  exchange_type: topic
  exchange_durable: True

plugind:
  host: localhost
  port: 9503
  verify_certificate: /usr/share/xivo-certs/server.crt

provd:
  host: localhost
  port: 8666
  verify_certificate: /usr/share/xivo-certs/server.crt

dird:
  host: localhost
  port: 9489
  version: 0.1
  verify_certificate: /usr/share/xivo-certs/server.crt

confd:
  host: localhost
  port: 9486
  verify_certificate: /usr/share/xivo-certs/server.crt

webhookd:
  host: localhost
  port: 9300
  version: 1.0
  verify_certificate: /usr/share/xivo-certs/server.crt
